### ISSUE TITLE
add "purge" method

### ISSUE THREAD

**Issue by david415** [krl/appendix#1]
There needs to be a way to destroy/remove data from disk.

**Comment by krl** [comment]
The tricky part is that you lose the guarantee that pointers into the structure are always valid. If you want to have a go at this, i would be interested how, i'm thinking about the same issue in an as of yet unpublished library on top of this.

**Comment by david415** [comment]
what? I don't understand what the problem is. I want a helper method that REMOVES ALL DATA. Why is there any problem with pointers? Consume all pointers with move semantics. Remove all data from disk. Done. Finito. Fin.

**Comment by david415** [comment]
OK. I submitted a pull request:
https://github.com/krl/appendix/pull/2

I would guess this will not be to your liking since you have mentioned your concern about honoring the guarantee of the pointers. What do you think of this pull request?
