### ISSUE TITLE
Index should have its Send and Sync traits be bounded.

### ISSUE THREAD

**Issue by ammaraskar** [krl/appendix#6]
Hi there, we (Rust group @sslab-gatech) are scanning crates on crates.io for potential soundness bugs. We noticed that the `Index` object implements the `Send` and `Sync` traits for all types:

https://github.com/krl/appendix/blob/b279bc230bfd5df4695c7a095f687d5c3a184e97/src/lib.rs#L61-L62

This should likely be bounded when both `K` and `V` are `Send` and `Sync` respectively, otherwise it makes it possible to send an `Index` object across threads containing non-Sendable types such as an `Rc` object or a `Cell`.

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by krl** [comment]
Thank you for your checkup! This has been fixed in 0.2.1
